rpb deb bugs Fixes #50 Fixes #129

diff --git a/deb/preinst b/deb/preinst
--- a/deb/preinst
+++ b/deb/preinst
@@ -8,6 +8,11 @@ if [[ "$1" == "install" || "$1" == "upgrade" ]]; then
     if systemctl list-units --full -all | grep -Fq 'harvest.service'; then
       systemctl stop harvest && echo "stopped harvest ..."
     fi
+    # Stop any harvest process which are not under systemctl
+    ps -ef | grep -w -- --poller | grep -w bin/poller | awk '{print $2}' | xargs -r kill
+    if [ $? -ne 0 ]; then
+       echo "  --> Error while stopping pollers"
+    fi
     if [  -e /usr/bin/harvest ]; then
       unlink /usr/bin/harvest && echo " --> delete link"
     fi
