rpb deb bugs Fixes #50 Fixes #129

diff --git a/deb/prerm b/deb/prerm
--- a/deb/prerm
+++ b/deb/prerm
@@ -6,6 +6,11 @@
 
 echo " --> stop harvest for $1"
 systemctl stop harvest
+# Stop any harvest process which are not under systemctl
+ps -ef | grep -w -- --poller | grep -w bin/poller | awk '{print $2}' | xargs -r kill
+if [ $? -ne 0 ]; then
+  echo "  --> Error while stopping pollers"
+fi
 if [ -e /opt/harvest/harvest.yml ]; then
   echo " --> backing up harvest conf"
   cp /opt/harvest/harvest.yml /opt/harvest/backup_harvest.yml
